"use client"
import Navbar from '@/components/Navbar'
import '../css/globals.css'
import Footer from '@/components/Footer'
import ProgressBar from 'next-nprogress-bar';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        {children}
        <ProgressBar
          height="4px"
          color="#641ae6"
          options={{ showSpinner: false }}
          shallowRouting
          appDirectory
        />
        <Footer/>
        </body>
    </html>
  )
}
